/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define STR_LEN 30
#define STR_LEN_VER 10

#if defined(__STDC__) || defined(__cplusplus)
#define conta 1
extern  int * conta_10(char **, CLIENT *);
extern  int * conta_10_svc(char **, struct svc_req *);
extern int str_len_10_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define conta 1
extern  int * conta_10();
extern  int * conta_10_svc();
extern int str_len_10_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
