/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MAGAZ_RPC 30
#define MAGZ_VER 20

#if defined(__STDC__) || defined(__cplusplus)
#define isItemQtaAvail 1
extern  int * isitemqtaavail_20(char **, CLIENT *);
extern  int * isitemqtaavail_20_svc(char **, struct svc_req *);
extern int magaz_rpc_20_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define isItemQtaAvail 1
extern  int * isitemqtaavail_20();
extern  int * isitemqtaavail_20_svc();
extern int magaz_rpc_20_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
